### ISSUE TITLE
ojet build android --release --build-config=buildConfig.json ERROR

### ISSUE THREAD

**Issue by felixliuxf** [oracle/ojet-cli#1]
I want to ojet build release APK file .
when I declare a variable using let ,the build will raise an error. 

D:\Apps\medicine>ojet build android --release --build-config=buildConfig.json
 Oracle JET Tooling
cleaning staging path.....
copy files to staging directory.....
copy finished...
copy library files to staging directory.....
copy finished...
optimizing svg into SVG sprites.....
svg task finished...
compiling sass....
sass compile finished...
running theme copy task.....
theme copy finished...
running theme injection task.....
indexHtml theme path injection finished..
injecting index.html with cordova script...
running injection task.....
mainJs paths injection finished..
running uglify tasks.....
Error: SyntaxError: Unexpected token: name (pageTitle1)

**Comment by peppertech** [comment]
Hi Felix,  this is happening because of an older version of Uglify being using in the JET tooling that did not support ES6 syntax.  Please update to the latest version of JET (v5.0.0) which was released just yesterday (April 16).  This issue has been fixed there with a new version of Uglify that is fully ES6 compliant.

**Comment by asksureshkumar** [comment]
D:\ojet\client>ojet build web --release
 Oracle JET Tooling
cleaning staging path.....
copy files to staging directory.....
copy finished...
copy library files to staging directory.....
copy finished...
compiling sass....
sass compile finished...
running theme injection task.....
indexHtml theme path injection finished..
running theme copy task.....
theme copy finished...
running injection task.....
mainJs paths injection finished..
running uglify tasks.....
Error: SyntaxError: Unexpected token: punc ())

D:\ojet\client>ojet --version
Oracle JET Command Line Interface, version: 5.1.0

Still getting same error in OJET v5.1.0.
Please let me know, If there are any workaround for this issue.

**Comment by peppertech** [comment]
What version of Node and npm are you using?
Please provide the results of:

node --version
npm -v

**Comment by peppertech** [comment]
Closing since no reply in over 6 months.  Re-open if you every come back with the requested info.
