### ISSUE TITLE
Error: Error: ENOENT: no such file or directory, open 'MySampleApp\hybrid\platforms\platforms.json'

### ISSUE THREAD

**Issue by papcai** [oracle/ojet-cli#2]
When I save a change to dashboard.html in an application, I get a error Error: Error: ENOENT: no such file or directory, open 'C:\Users\papcai\Desktop\MySampleApp\hybrid\platforms\platforms.json'.

My command line:

C:\Users\papcai\Desktop\MySampleApp> **ojet serve android --browser**
Build: true
BuildType: dev
Destination: browser
Destination target: chrome
Livereload: true
Livereload port: 35729
Platform: android
Theme: alta
Theme platform: android
Theme version: 5.0.0
Building app.
Cleaning staging path.
Running before_build hook.
(node:3772) ExperimentalWarning: The fs.promises API is experimental
Cleaning staging path.
Copy files to staging directory.
Copy finished.
Copy library files to staging directory.
Copy finished.
Optimizing svg into SVG sprites.
Svg optimisation task finished.
Compiling sass.
Sass compile finished.
Task index.html cdn bundle injection finished.
Running theme copy task.
Theme copy task finished.
Running theme injection task.
Task index.html theme path injection finished.
Injecting index.html with cordova script.
Running injection tasks.
Task main.js paths injection finished.
Running after_build hook.
Running before_serve hook.
Executing: cmd.exe /s /c cordova serve
Android Studio project detected

Error:Error: ENOENT: no such file or directory, open 'C:\Users\papcai\Desktop\MySampleApp\hybrid\platforms\android\res\xml\config.xml'

Static file server running on: http://localhost:8006 (CTRL + C to shut down)
Executing: cmd.exe /s /c cordova run browser -- --target="chrome"

startPage = index.html

Static file server running @ http://localhost:8007/index.html
CTRL + C to shut down

Starting watcher.
Running after_serve hook.
Listening on port 35729.
Watching files.
Watcher: sass is ready.
Watcher: sourceFiles is ready.
200 /index.html (gzip)
200 /js/cordovaMocks.js
200 /css/app.css
200 /cordova.js (gzip)
200 /js/main.js (gzip)
200 /js/libs/require/require.js (gzip)
200 /css/demo-alta-site-min.css (gzip)
200 /css/alta/5.0.0/android/alta.css (gzip)
200 /cordova_plugins.js
200 /js/appController.js (gzip)
200 /js/libs/oj/v5.0.0/debug/ojcore.js (gzip)
200 /js/libs/oj/v5.0.0/debug/ojmodule.js (gzip)
200 /js/libs/oj/v5.0.0/debug/ojrouter.js (gzip)
200 /js/libs/oj/v5.0.0/debug/ojknockout.js (gzip)
200 /js/libs/knockout/knockout-3.4.2.debug.js (gzip)
200 /js/libs/oj/v5.0.0/debug/ojmodule-element-utils.js (gzip)
200 /js/libs/oj/v5.0.0/debug/ojmodule-element.js (gzip)
200 /js/libs/oj/v5.0.0/debug/ojnavigationlist.js (gzip)
200 /js/libs/oj/v5.0.0/debug/ojmoduleanimations.js (gzip)
200 /js/libs/oj/v5.0.0/debug/ojarraytabledatasource.js (gzip)
200 /js/libs/oj/v5.0.0/ojL10n.js (gzip)
200 /js/libs/es6-promise/es6-promise.js (gzip)
200 /js/libs/oj/v5.0.0/debug/ojkoshared.js (gzip)
200 /js/libs/jquery/jqueryui-amd-1.12.1/widget.js (gzip)
200 /js/libs/js-signals/signals.js (gzip)
200 /js/libs/oj/v5.0.0/debug/ojcomposite.js (gzip)
200 /js/libs/oj/v5.0.0/debug/ojanimation.js (gzip)
200 /js/libs/oj/v5.0.0/debug/ojdatasource-common.js (gzip)
200 /js/libs/jquery/jqueryui-amd-1.12.1/version.js
200 /js/libs/oj/v5.0.0/resources/nls/ojtranslations.js (gzip)
200 /js/libs/jquery/jquery-3.3.1.js (gzip)
200 /js/libs/oj/v5.0.0/debug/ojcomposite-knockout.js (gzip)
200 /js/libs/oj/v5.0.0/debug/ojcustomelement.js (gzip)
200 /js/libs/oj/v5.0.0/debug/ojbutton.js (gzip)
200 /js/libs/oj/v5.0.0/debug/ojmenu.js (gzip)
200 /js/libs/oj/v5.0.0/debug/ojcomponentcore.js (gzip)
200 /js/libs/oj/v5.0.0/debug/ojlistview.js (gzip)
200 /js/libs/webcomponents/custom-elements.min.js (gzip)
200 /js/libs/oj/v5.0.0/debug/ojjquery-hammer.js (gzip)
200 /js/libs/oj/v5.0.0/debug/ojoption.js (gzip)
200 /js/libs/hammer/hammer-2.0.8.js (gzip)
200 /js/libs/oj/v5.0.0/debug/ojpopupcore.js (gzip)
200 /js/libs/jquery/jqueryui-amd-1.12.1/unique-id.js
200 /js/libs/jquery/jqueryui-amd-1.12.1/keycode.js
200 /js/libs/jquery/jqueryui-amd-1.12.1/tabbable.js
200 /js/libs/jquery/jqueryui-amd-1.12.1/focusable.js (gzip)
200 /js/libs/oj/v5.0.0/debug/ojmessaging.js (gzip)

200 /js/libs/oj/v5.0.0/debug/ojdomscroller.js (gzip)
200 /js/libs/oj/v5.0.0/debug/ojkeyset.js (gzip)
200 /js/libs/oj/v5.0.0/debug/ojdataprovideradapter.js (gzip)
200 /js/libs/jquery/jqueryui-amd-1.12.1/position.js (gzip)

200 /js/libs/oj/v5.0.0/debug/ojeventtarget.js (gzip)

200 /js/libs/oj/v5.0.0/debug/ojdataprovider.js (gzip)

Watcher: themes is ready.
200 /css/fonts/App_iconfont.woff

200 /js/libs/require/text.js (gzip)

200 /js/viewModels/dashboard.js (gzip)

200 /js/views/dashboard.html

200 /js/views/header.html

**Changed: C:\Users\papcai\Desktop\MySampleApp\src\js\views\dashboard.html
Error: Error: ENOENT: no such file or directory, open 'C:\Users\papcai\Desktop\MySampleApp\hybrid\platforms\platforms.json'**
PS C:\Users\papcai\Desktop\MySampleApp>

**Comment by rshashik** [comment]
Hi,
I am getting  below error when i try to build OJET Application. 
do we need to manually create config.xml file or automatically created??

OJET version: 5.2.0

Error:Error: ENOENT: no such file or directory, open 'C:\Users\UserName\MySampleApp\hybrid\platforms\android\res\xml\config.xml'

**Comment by peppertech** [comment]
This is an error thrown by the Cordova tools.  It can be ignored.  The
application will continue to build and run just fine.

If that is not what you are seeing, please let us know.

**Comment by chesiver** [comment]
I also encountered this issue but had no idea what caused it.
I manually created a platform.json to avoid this.
