### ISSUE TITLE
navdrawer template is not working 

### ISSUE THREAD

**Issue by rshashik** [oracle/ojet-cli#3]
oracleJet version 5.2.0  
npm version : '5.6.0' 
node v8.11.4

**Command:** C:\Users\UserName>ojet create JET_Web_Application --template=navdrawer
**Error:** 
npm ERR! path C:\Users\Username\JET_Web_Application1\node_modules\requirejs\bin\r.js.2578835334
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\Username\JET_Web_Application1\node_modules\requirejs\bin\r.js.2578835334' -> 'C:\Users\Username\JET_Web_Application1\node_modules\requirejs\bin\r.js'
npm ERR!  { Error: EPERM: operation not permitted, rename 'C:\Users\Username\JET_Web_Application1\node_modules\requirejs\bin\r.js.2578835334' -> 'C:\Users\Username\JET_Web_Application1\node_modules\requirejs\bin\r.js'
npm ERR!   cause:
npm ERR!    { Error: EPERM: operation not permitted, rename 'C:\Users\Username\JET_Web_Application1\node_modules\requirejs\bin\r.js.2578835334' -> 'C:\Users\Username\JET_Web_Application1\node_modules\requirejs\bin\r.js'
npm ERR!      errno: -4048,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'rename',

**Comment by peppertech** [comment]
This is indicating that you do not have the proper permissions.  Do you have Admin rights to the machine?
Make sure you have Admin rights when installing the ojet-cli or any NPM module that where you use the " -g " flag.  You can try running your command window "As Administrator".

**Comment by rshashik** [comment]
Yes. I have Admin rights.
This issue is coming only for navdrawer template. I am able to create project with other templates.

**Comment by peppertech** [comment]
Wow, that's really weird.  The templates are all pulled from the same location. The only thing that I can think of to try next would be to clear the npm cache and try again.  That navdrawer template file is used 100's of times a day without any issues, so we know that it's not an issue with the template itself.

**Comment by peppertech** [comment]
Not reproduceable.
