### ISSUE TITLE
unable to create | phantomjs-prebuilt@2.1.16: this package is now deprecated

### ISSUE THREAD

**Issue by saideep-g** [oracle/ojet-cli#7]
When executing `ojet create`, below error is thrown:

`PS D:\Projects\nodejs> ojet create myApp
Processing template: blank
Your app structure is generated. Continuing with library install.
(node:16104) UnhandledPromiseRejectionWarning: Error: Command failed: npm install
npm WARN deprecated phantomjs-prebuilt@2.1.16: this package is now deprecated
npm ERR! code Z_BUF_ERROR
npm ERR! errno -5
npm ERR! zlib: unexpected end of file`

Can you please get this fixed?

**Comment by peppertech** [comment]
can you please provide the results of this command

ojet --version

This sounds like you are using a very old version of the CLI.  Phantom is a 4th party dependency for the tooling.  We don't directly load it so it's not something that we can fix, but this old of a version has not been used in a long time.

Please also check your version of Node.  We require a min version of 8.x for running the latest JET CLI.  We always recommend that developers use the LTS release of Node when possible.

**Comment by peppertech** [comment]
Digging into this a little bit more.  The svg-sprite library is the one that is pulling in the phantomjs-prebuilt library.  It should install properly if you have your internet connections setup properly though.

Can you do a manual install of this library?

I'm not able to reproduce you error message on any of my local machines.  Maybe a few more details about your environment would help.  

OS (type and version)
Browser (vendor and version)
Node version
NPM version
JET version

Thanks

**Comment by saideep-g** [comment]
`PS D:\Projects\nodejs\oracle-jet> ojet --version
Oracle JET Command Line Interface, version: 7.2.0`

![image](https://user-images.githubusercontent.com/11366144/67618807-920d7a00-f811-11e9-9f45-50282510be15.png)

**Node/NPM/OJET Version:**

> PS D:\Projects\nodejs\oracle-jet> node --version
> v10.13.0
> PS D:\Projects\nodejs\oracle-jet> npm --version
> 6.4.1
> PS D:\Projects\nodejs\oracle-jet> ojet --version
> Oracle JET Command Line Interface, version: 7.2.0

**My OS:**
![image](https://user-images.githubusercontent.com/11366144/67618853-1fe96500-f812-11e9-93f2-321da550b108.png)

Browser details:
Chrome _(Version 77.0.3865.120 (Official Build) (64-bit))_

**Comment by saideep-g** [comment]
Further, I am able to install `phantomjs-prebuilt` on its own without any issue. See the log below:

```
PS D:\Projects\nodejs\oracle-jet> npm install phantomjs-prebuilt
npm WARN deprecated phantomjs-prebuilt@2.1.16: this package is now deprecated

> phantomjs-prebuilt@2.1.16 install D:\Projects\nodejs\oracle-jet\node_modules\phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-windows.zip
Saving to C:\Users\139164\AppData\Local\Temp\phantomjs\phantomjs-2.1.1-windows.zipReceiving...
  [========================================] 100%
Received 17767K total.
Extracting zip contents
Removing D:\Projects\nodejs\oracle-jet\node_modules\phantomjs-prebuilt\lib\phantomCopying extracted folder C:\Users\139164\AppData\Local\Temp\phantomjs\phantomjs-2.1.1-windows.zip-extract-1572089758602\phantomjs-2.1.1-windows -> D:\Projects\nodejs\oracle-jet\node_modules\phantomjs-prebuilt\lib\phantom
Writing location.js file
Done. Phantomjs binary available at D:\Projects\nodejs\oracle-jet\node_modules\phantomjs-prebuilt\lib\phantom\bin\phantomjs.exe
npm WARN saveError ENOENT: no such file or directory, open 'D:\Projects\nodejs\oracle-jet\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'D:\Projects\nodejs\oracle-jet\package.json'
npm WARN oracle-jet No description
npm WARN oracle-jet No repository field.
npm WARN oracle-jet No README data
npm WARN oracle-jet No license field.

+ phantomjs-prebuilt@2.1.16
added 81 packages from 76 contributors and audited 102 packages in 21.957s
found 0 vulnerabilities
```

**Comment by peppertech** [comment]
Thanks Sai,  if you can install it directly, I would just recommend trying
the ojet create command again and see if it works this time.

The recommended command is:

ojet create myApp --template=<one of three default templates basic, navbar,
and navdrawer>

If you do choose to use the "blank" template, which is what you get when
you don't use the template command, you should have a very good
understanding of how all of the configuration works, as you will have to
set it all up yourself.

I have basically the same setup that you do, and I can not reproduce this
error.

--jb

**Comment by saideep-g** [comment]
Thanks John. I have done global install and tried to create App; but no luck. Below is the log:

```
PS D:\Projects\nodejs\oracle-jet> npm install -g phantomjs-prebuilt@2.1.16
npm WARN deprecated phantomjs-prebuilt@2.1.16: this package is now deprecated
C:\Users\139164\AppData\Roaming\npm\phantomjs -> C:\Users\139164\AppData\Roaming\npm\node_modules\phantomjs-prebuilt\bin\phantomjs

> phantomjs-prebuilt@2.1.16 install C:\Users\139164\AppData\Roaming\npm\node_modules\phantomjs-prebuilt
> node install.js

Considering PhantomJS found at C:\Users\139164\AppData\Roaming\npm\phantomjs.CMD
Looks like an `npm install -g` on windows; skipping installed version.
Download already available at C:\Users\139164\AppData\Local\Temp\phantomjs\phantomjs-2.1.1-windows.zip
Verified checksum of previously downloaded file
Extracting zip contents
Removing C:\Users\139164\AppData\Roaming\npm\node_modules\phantomjs-prebuilt\lib\phantom
Copying extracted folder C:\Users\139164\AppData\Local\Temp\phantomjs\phantomjs-2.1.1-windows.zip-extract-1572282726153\phantomjs-2.1.1-windows -> C:\Users\139164\AppData\Roaming\npm\node_modules\phantomjs-prebuilt\lib\phantom
Writing location.js file
Done. Phantomjs binary available at C:\Users\139164\AppData\Roaming\npm\node_modules\phantomjs-prebuilt\lib\phantom\bin\phantomjs.exe
+ phantomjs-prebuilt@2.1.16
added 81 packages from 76 contributors in 4.526s
PS D:\Projects\nodejs\oracle-jet> ojet create myApp --template=navdrawer
Processing template: navdrawer
Your app structure is generated. Continuing with library install.
(node:15396) UnhandledPromiseRejectionWarning: Error: Command failed: npm install
npm WARN deprecated phantomjs-prebuilt@2.1.16: this package is now deprecated
npm ERR! code Z_BUF_ERROR
npm ERR! errno -5
npm ERR! zlib: unexpected end of file

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\139164\AppData\Roaming\npm-cache\_logs\2019-10-28T17_12_23_865Z-debug.log

    at ChildProcess.exithandler (child_process.js:289:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
(node:15396) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id:
1)
(node:15396) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
PS D:\Projects\nodejs\oracle-jet>
```
I tried this in gitbash aswell; but got same result. Please advise.

**Comment by benm071** [comment]
What's in that 2019-10-28T17_12_23_865Z-debug.log file?

Have you tried to do an "npm cache clean --force" and try the create command?

**Comment by saideep-g** [comment]
Thanks Ben. That worked.

```
PS D:\Projects\nodejs\oracle-jet> npm cache clean --force
npm WARN using --force I sure hope you know what you are doing.
PS D:\Projects\nodejs\oracle-jet> ojet create myApp --template=navdrawer
Processing template: navdrawer
Your app structure is generated. Continuing with library install.
Writing:
oraclejetconfig.json
oraclejetconfig.json file exists. Checking config.
Running after_app_create hook.
Your app is ready! Change to your new app directory 'myApp' and try 'ojet build' and 'ojet serve'.
PS D:\Projects\nodejs\oracle-jet>
```

**Comment by silviuburceadev** [comment]
I'm guessing that this can be closed, since there is a valid resolution.

**Comment by saideep-g** [comment]
Yes. Please close. Thanks.
