### ISSUE TITLE
jet-composites adds 'version' on runtime/ build

### ISSUE THREAD

**Issue by baysoft** [oracle/ojet-cli#8]
When working with jet-composite, during **build/serve** it adds an additional folder 'version'???
Look at this image below:
![2020-04-29_LI](https://user-images.githubusercontent.com/11055315/80619486-f46c5f00-8a6e-11ea-9d5f-6d7df060c06e.jpg)

This code **will not** work:
``` javascript
require(['ojs/ojbootstrap', 'knockout', 'ojs/ojknockout', './jet-composites/demo-card/loader'],
    function (Bootstrap, ko) {
        function Model() {
            //...
        }
    }
);
```
I have to modify it to:
``` javascript
require(['ojs/ojbootstrap', 'knockout', 'ojs/ojknockout', './jet-composites/demo-card/8.2.0/loader'],
    function (Bootstrap, ko) {
        function Model() {
            //...
        }
    }
);
```
Thanks ...

**Comment by peppertech** [comment]
Remove the reference to /jet-composites/ completely and only use the name of the component and loader.  "demo-card/loader"

**Comment by peppertech** [comment]
The tooling adds a path reference in the requirejs config for your component and places the version number in the path to help with cache busting on the client.

**Comment by baysoft** [comment]
The tooling adds a path reference using assumption that the initialization file is **'main.js'** ?
If there are more than one initialization file, ie. main.js and xxxx.js, but the file I use is xxxx.js, like this:
```html
   file: index.html
   ...
   \\remove for brevity
  <script type="text/javascript" src="js/libs/require/require.js"></script>
  <script type="text/javascript" src="js/xxxx.js"></script>
</body>
```
it does not work (path reference always added to main.js)
Thank you and please forgive my poor english.

**Comment by peppertech** [comment]
Yes, the tooling expects to find main.js.  It is really the only file you can not rename or change when using the JET CLI tooling.

You should rarely if ever have to change that file.  If you want to add other module path mappings you should use the path_mappings.js file, or if you want to add additional code that gets call at initialization, create your own module and add a dependency on it in main.js.

And you English is great.  Far better than myself trying to speak your native language I am sure. :-)
