### ISSUE TITLE
Injecting build-time environment variables

### ISSUE THREAD

**Issue by florsluis** [oracle/ojet-cli#9]
Is there any way to access environment variables to configure development/production URLs. Typically on build time I would be able to use `process.env.NODE_ENV` variable to make this decision on build time but this is not available within the RequireJS modules.

**Comment by peppertech** [comment]
The use of the build hook scripts would provide you access to this. https://docs.oracle.com/en/middleware/developer-tools/jet/15/develop/understand-web-application-workflow.html#GUID-D19EC0A2-DFEF-4928-943A-F8CC08961453
